config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  	resources :projects
 	resources :properties
  	root 'welcome#index'
    get :send_order_mail, to: 'projects#send_order_mail', as: :send_order_mail


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/project.rb
class Project < ApplicationRecord
	has_attached_file :image, styles: {large: "600x600>",medium: "300x300>",thumb: "150x150#"} ,default_url: "/assets/:style/no_image.jpg"
	validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
	validates_presence_of :location
	validates :price, presence: true,numericality: { only_integer: true }
	validates :area, presence: true,numericality: { only_integer: true }
	validates_presence_of :developer_name ,length: {minimum: 3}
	validates :developer_name, format: { with: /\A[a-zA-Z]\D/,
		message: "Only letters is allowed" }
	before_validation { image.clear if @delete_image }
	belongs_to :user
	belongs_to :property
	def delete_image
    	@delete_image ||= false
  	end

  	def delete_image=(value)
    	@delete_image  = !value.to_i.zero?
  	end
	def self.search(search)	
  		joins(:property).where("location LIKE ? OR developer_name LIKE ? OR properties.name LIKE ? OR price LIKE ? OR area LIKE ?", "%#{search}%","%#{search}%","%#{search}%","%#{search}%","%#{search}%")
	end
	
end

app/models/property.rb
class Property < ApplicationRecord
	validates :name, presence: true, length: { minimum: 3 }, uniqueness: true
	has_many :projects, dependent: :destroy
	belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  validates :username, presence: true, length: { minimum: 3 }
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :projects
  has_many :properties
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_filter :configure_permitted_parameters, if: :devise_controller?
  protected
	def configure_permitted_parameters
            devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:username, :email, :password) }
            devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:username, :email, :password, :current_password, ) }
    end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :authenticate_user!, except: [:index,:show]
	def index
    @projects = Project.all
    if params[:search]
      @projects = Project.search(params[:search]).order("created_at DESC")
    else
      @projects = Project.all.order('created_at DESC')
    end
  end
  def show
    @project = Project.find(params[:id])
  end
	def new
		 @project = current_user.projects.build
		 @properties= Property.pluck(:name, :id )
	end
	def edit
  		@project = Project.find(params[:id])
  		@properties= Property.pluck(:name, :id)
	end
	def create
  		@project = current_user.projects.build(project_params)
      @project.property_id = params[:property_id] 
      @properties= Property.pluck(:name, :id)
    if @project.save  
      redirect_to @project
    else
      render :new
    end
	end
  def update
    @project = Project.find(params[:id])
    @project.property_id = params[:property_id] 
    @properties= Property.pluck(:name, :id)
    if @project.update(project_params)
      redirect_to @project
    else
      render :edit
    end
  end
  def destroy
    @project = Project.find(params[:id])
    if @project.destroy
      redirect_to projects_path, notice: "Successfully destroyed"
    else
      redirect_to @project, notice: "Not destroyed"
    end
  end
  def send_order_mail
     @project = Project.find(params[:id])
     ProjectMailer.sample_email(current_user, @project.user).deliver
      flash[:notice] = "mail has been sent."
      redirect_to project_path(@project.id)
  end
  private
    def project_params
    params.require(:project).permit(:property_id,:location,:price,:area,:developer_name,:sold,:image,:delete_image)
  end
end

app/controllers/properties_controller.rb
class PropertiesController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  def index
    @properties = Property.all
    end
  def show
    @property = Property.find(params[:id])
    end
  def new
     @property = current_user.properties.build
  end
  def edit
      @property = Property.find(params[:id])
  end
  def create
      @property = current_user.properties.build(property_params)
    if @property.save
      redirect_to properties_path
    else
      render :new
    end
  end
  def update
    @property = Property.find(params[:id])
      if @property.update(property_params)
        redirect_to @property
      else
      render 'edit'
      end
  end
  def destroy
    @property = Property.find(params[:id])
    if  @property.destroy
      redirect_to properties_path, notice: "Successfully destroyed"
    else
      redirect_to @property, notice: "Not destroyed"
    end
  end
  private
    def property_params
      params.require(:property).permit(:name,:user_id)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/devise_helper.rb
module DeviseHelper
 def devise_error_messages!
  return '' if resource.errors.empty?

   messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
   sentence = I18n.t('errors.messages.not_saved',
   count: resource.errors.count,
   resource: resource.class.model_name.human.downcase)

   html = <<-HTML
   <div class="alert alert-error alert-block"> <button type="button"
    class="close" data-dismiss="alert">x</button>
    <h4>#{sentence}</h4>
    #{messages}
   </div>
   HTML

   html.html_safe
 end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/properties_helper.rb
module PropertiesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/_navbar.html.erb
<div class="container-fluid">
 <nav class="navbar navbar-default navbar-static-top navbar-custom ">
   <div>
      <div class="navbar-header">
         <%= link_to "Home", root_path, class: "navbar-brand" %>
      </div>
      <ul class="nav navbar-nav navbar-right">
         <li ><%= link_to 'List of Project', projects_path %></li>
      	<li ><%= link_to 'New Project', new_project_path %></li>
         <li ><%= link_to 'New property type', new_property_path %></li>
         <% if user_signed_in? %>
            <li class="toppad"><%= current_user.username %></li>
            <li class="rtpad">
               <%= link_to('Logout', destroy_user_session_path, method: :delete) %>        
            </li>
         <% else %>
            <li>
               <li ><%= link_to 'Sign up ', new_user_registration_path %></li>
               <li class="rtpad"><%= link_to 'Log in ', new_user_session_path %></li>
            </li>
         <% end %>
      </ul>
    </div>
 </nav>
</div>

app/views/layouts/application.html.erb
<html>
  <head>
     <title>Real Estate</title>
     <%= stylesheet_link_tag    'application', media: 'all' %>
     <%= javascript_include_tag 'application' %>
     <%= csrf_meta_tags %>
     <link href="path/to/lightbox.css" rel="stylesheet">
  </head>
  <body>
  <div class="container-fluid">
  <%= render "layouts/navbar" %>
   </div>
     <div class="container">
     <p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>

       <%= yield %>
       <%= javascript_tag do %>
         <%= yield :javascript %>
       <% end %>
       <footer class="rtpad" align= right>
          <p></p>
       </footer>
      </div>
      <div class="modal-container"></div>
      <script src="path/to/lightbox.js"></script>
   </body>
</html>

app/views/projects/edit.html.erb
<div class="container-fluid">
  <h3>Back to: <%= link_to 'List of Projects', projects_path %></h3>
  <div class="container formstyle" align="center">
    <h1>Edit Project</h1><br/>
    <%= form_for :project, url: project_path(@project), method: :patch do |f| %>
      <% if @project.errors.full_messages.any? %>
        <h2>Errors</h2>
        <% @project.errors.full_messages.each do |error_message| %>
        <%= error_message if @project.errors.full_messages.first == error_message %> <br />
      <% end %>
    <% end %><br/>
      <p>
        <%= f.label :property_type %>:
        <%= select_tag(:property_id, options_for_select(@properties)) %>
      </p>
      <p>
        <%= f.label :location %>:
        <%= f.select :location, [ 'Mumbai', 'Delhi', 'Kolkata','Kota','Bangalore','Durgapur'], :prompt => 'Select One' %>
      </p>
      <p>
        <%= f.label :price %> (&#x20B9;)<br>
        <%= f.text_field :price %>
      </p>
      <p>
        <%= f.label :area %> (in sqft)<br>
        <%= f.text_field :area %>
      </p>
      <p>
        <%= f.label :developer_name %><br>
        <%= f.text_field :developer_name %>
      </p>
      <p>
        <% if @project.image.exists? %>
          <%= image_tag @project.image.url(:thumb) %><br/>
          <%= f.check_box :delete_image %>Delete Image<br/>
        <% end %>
        <%= f.file_field :image %>
      </p>  
      <p>
        <%= f.label :Status %><br>
        <%= f.text_field :sold %>
      </p>
      <p>
        <%= f.submit %>
      </p>
    <% end %>
  </div>
</div>

app/views/projects/index.html.erb
<div class="container">
  <div class="container" align="right">
    <%= form_tag(projects_path, :method => "get", id: "search-form") do %>
      <%= text_field_tag :search, params[:search], placeholder: "Search Projects" %>
      <%= submit_tag "Search",:name => nil %>
    <% end %>
    <% if @projects.present? %>
      <% @projects %>
    <% else %>
      <p>There are no posts containing the term(s) <%= params[:search] %>.</p>
    <% end %>
  </div>
  <div class="container formstyle-2">
    <h1>List of Projects</h1>
    <table >
      <tr class="botpad">
        <th>Image &nbsp;</th>
        <th>Property Type &nbsp;&nbsp;&nbsp;</th>
        <th>Location &nbsp;</th>
        <th>Price (&#x20B9;)&nbsp;</th>
        <th>Area (in sqft)&nbsp;</th>
        <th>Developer Name &nbsp;&nbsp;&nbsp;</th>
        <th>Status&nbsp; &nbsp;</th>
      </tr>
      <% @projects.each do |project| %>
        <tr>
          <td ><%= image_tag project.image.url(:thumb) %></td>
          <td><%= link_to Property.find(project.property_id).name, properties_path%>&nbsp; &nbsp; &nbsp;</td>
          <td><%= project.location%>&nbsp; &nbsp; &nbsp;</td>
          <td><%= project.price %>&nbsp; &nbsp; &nbsp;</td>
          <td><%= project.area%>&nbsp;</td>
          <td><%= project.developer_name %>&nbsp; &nbsp; &nbsp;</td>
          <td><%= project.sold %>&nbsp;</td>
          <td><h4 border :none>&nbsp; &nbsp; &nbsp;<%= link_to 'Show', project_path(project) %>&nbsp; &nbsp; &nbsp;
          <% if project.user == current_user %>
            <%= link_to 'Edit',edit_project_path(project) %>&nbsp; &nbsp;<%= link_to 'Destroy', project_path(project),method: :delete,data: { confirm: 'Are you sure?' } %></h4> 
          <% end %>
          </td>
        </tr>
      <% end %>
    </table>
  </div>
</div>

app/views/projects/new.html.erb
<h3>Back to: <%= link_to 'List of Projects', projects_path %></h3>
<div class="conatiner formstyle" align="center">
  <h1>Create New Project</h1><br/>
  <%= form_for :project, url: projects_path, html: { multipart: true } do |f| %>
   <p>
    <% if @project.errors.full_messages.any? %>
      <h2>Errors</h2><br/>
      <% @project.errors.full_messages.each do |error_message| %>
      <%= error_message if @project.errors.full_messages.first == error_message %> <br />
      <% end %>
    <% end %>
      <%= f.label :property_type %>:
      <%= select_tag(:property_id, options_for_select(@properties)) %>
    </p>
    <p>
      <%= f.label :location %>
      <%= f.select :location, [ 'Mumbai', 'Delhi', 'Kolkata','Kota','Bangalore','Durgapur'], :prompt => 'Select One' %>
      </p>
    <p>
      <%= f.label :price  %> (&#x20B9;)<br>
      <%= f.text_field :price %>
    </p>
    <p>
      <%= f.label :area %> (in sqft)<br>
      <%= f.text_field :area %>
    </p>
    <p>
      <%= f.label :developer_name %><br>
      <%= f.text_field :developer_name %>
    </p>
    <p>
    <p>
      <%= f.label :image  %><br>
      <%= f.file_field :image %>
    </p>
      <%= f.submit %>
    </p>
  <% end %>
  <h3>Back to: <%= link_to 'Projects', projects_path %></h3> 
</div>

app/views/projects/show.html.erb
<h3>Back to: <%= link_to 'List of Projects', projects_path %></h3>

<% if @project.user == current_user %>
  <h3 align="right">       <%= link_to 'Edit',edit_project_path(@project) %>&nbsp; &nbsp;</h3>
<% end %>
<div class="container formstyle" align="center">
 <h1>PROJECT</h1><br/>
 <% if @project.image.exists? %>
    <%= link_to (image_tag @project.image.url(:medium)), @project.image.url(:large)%>
    <% else %>
      <%= image_tag @project.image.url(:medium) %>
  <% end %>

  <p>
    <strong>Location :</strong>
    <%= @project.location %>
  </p>
  <p>
    <strong>Price (&#x20B9;) :</strong>
    <%= @project.price %>
  </p>
  <p>
    <strong>Area (in sqft) :</strong>
    <%= @project.area %>
  </p>
  <p>
    <strong>Developer’s name / Owner’s :</strong>
    <%= @project.developer_name%>
  </p>
  
  <p><% if @project.sold.nil? %>
        <strong>Status :</strong>
        <%= @project.sold%>
    <% end %>
  </p>
  <div align="center">
   <h3><%#= link_to "Interested :", controller: "projects", action: 
    "send_order_mail", id: @project.id %></h3>
  </div>
</div>

app/views/properties/edit.html.erb
<h3>Back to: <%= link_to 'Properties', properties_path %></h3>
<div class="container formstyle" align="center">
  <h1>Edit Property</h1><br/>
  <%= form_for :property, url: property_path(@property), method: :patch do |f| %>
    <% if @property.errors.full_messages.any? %>
      <h2>Errors</h2>
      <% @property.errors.full_messages.each do |error_message| %>
      <%= error_message if @property.errors.full_messages.first == error_message %> <br />
      <% end %>
    <% end %><br/>
    <p>
      <%= f.label :name %><br>
      <%= f.text_field :name %>
    </p>
    <p>
      <%= f.submit %>
    </p>
  <% end %>
</div>

app/views/properties/index.html.erb
<div class container></div>
<h3>Back to: <%= link_to 'List of Project', projects_path %></h3>
<div class="container formstyle" align="center">
  <h1>List of Property</h1>
  <table >
    <tr>
      <th><h3>Property Name</h3></th>
    <br/>
    <% @properties.each do |property| %>
      <tr>
        <td><%= property.name %>&nbsp; &nbsp; &nbsp;&nbsp; &nbsp; &nbsp;
        </td>
        <td><%= link_to 'Show', property_path(property) %></td>
        <td><% if property.user == current_user %>
              <%= link_to 'Edit', edit_property_path(property) %></td>
              <td><%= link_to 'Destroy', property_path(property),
                method: :delete,
                data: { confirm: 'Are you sure?' } %>
              </td>
          <%end %>
      </td>
    </tr>
    <% end %>
  </table>
</div>

app/views/properties/new.html.erb
<h3>Back to: <%= link_to 'List of Property', properties_path %></h3>
<div class="container formstyle" align="center">
	<h1>Create New Property</h1><br/>
	<%= form_for :property, url: properties_path do |f| %>
  	<% if @property.errors.full_messages.any? %>
      <h2>Errors</h2>
      <% @property.errors.full_messages.each do |error_message| %>
      <%= error_message if @property.errors.full_messages.first == error_message %> <br />
      <% end %>
    <% end %><br/>  		
    <p>
    		<%= f.label :name %><br>
    		<%= f.text_field :name %>
  		</p>
		<p>
    	<%= f.submit %>
    </p>
	<% end %>
</div>

app/views/properties/show.html.erb
<h3>Back to: <%= link_to 'Properties', properties_path %></h3>
<div class="container formstyle" align="center">
	<h1>Property</h1><br/>
	<p>
  		<strong>Property Name:</strong>
  		<%= @property.name%>
	</p>
</div>

app/views/welcome/index.html.erb
<div class="center jumbotron bgcolur">
  <h1>Real Estate Projects </h1>
  
</div>
  <div align="center">
  <%= button_to "Enter",projects_path, :id => "open-contacts-dialog-btn",:class => "inbox-sf-add-btn tip myButton", :method => :get %>
   </div>